### ISSUE TITLE
MAIN_MENUS_ADMIN_CLASS is not defined

### ISSUE THREAD

**Issue by frague59** [jazzband/wagtailmenus#505]
Hi, 

I'm working on a new Wagtail project and I've an issue with `wagtailmenus` app: 
```
cogwheels.exceptions.settings.DefaultValueNotImportable: There is an issue with the default value specified for MAIN_MENUS_ADMIN_CLASS in wagtailmenus.conf.defaults. No module could be found matching the path 'wagtailmenus.menuadmin'. Please use a full (not relative) import path with the object name at the end, for example: 'project.app.module.object'.
```

When looking in the `site-packages` directory, I can find the module but I cannot load it.

Wagtail==6.3.1
Django==4.2.17
wagtailmenus==4.0.1

Thanks for your help !

**Comment by frague59** [comment]
Please note the docs are not updated of RTD to match les new 4.x version.

**Comment by MrCordeiro** [comment]
Hi @frague59, the module exists, as you can see [here](https://github.com/jazzband/wagtailmenus/blob/master/wagtailmenus/menuadmin.py). I don't believe it is being caused by wagtailmenus but by cogwheels.

Thanks for letting us know about the issues with the docs. We are following that issue here: #488
